#!/bin/bash
# Fix directory permissions for EAS build
echo "Fixing directory permissions..."
chmod -R u+rwx .
echo "Permissions fixed."

# Remove lockfile generated by incompatible npm version so npm ci can regenerate
echo "Removing package-lock.json for fresh generation..."
rm -f package-lock.json
echo "Pre-install complete."
